### ISSUE TITLE
syntax is not ruby 2.0 compatible

### ISSUE THREAD

**Issue by hannahhoward** [krainboltgreene/architecture.gem#9]
Output of running tests on ruby 2.0:

```
/Users/hannah/projects/architecture.gem/spec/spec_helper.rb:4:in `require': /Users/hannah/projects/architecture.gem/lib/architecture.rb:22: syntax error, unexpected ',' (SyntaxError)
  private def architecture(source:, destination:, &block)
```

We're planning to support ruby-2.0 on Xing. It'd be great if the syntax could be made ruby 2.0 compatible since it's still a support version for the forseeable future

**Comment by hannahhoward** [comment]
I see now that you're using required keyword arguments throughout so this would be hard to remove -- I'll take discussions back to LRD and see what they want to do.

**Comment by krainboltgreene** [comment]
Okay, so we talked about this in person but I want to detail my thoughts here:

Realistically I can make a branch, change the keywords to regular arguments, release `7.0.0+mri2-0-0`.

However, I implore LRD to upgrade to 2.3.0, as it's relatively painless (2.1.X onward is even semver, so you know there are no breaking changes), and provides significant performance improvement!

**Comment by IdahoEv** [comment]
Kurtis,

We do use > 2.1 (usually 2.3, occasionally 2.2) internally, for everything. The challenge is that we are publishing a platform for others to use, not just us. And the more limited/constrained our requirements, the fewer other people will be able to use our platform.

The issue brought up by one of us is that in deployment a lot of people standardize on LTS linux distributions. Those distros tend to stay static for years, and don't have the option to follow the normal rapid upgrade path of e.g. Ruby.

**Comment by krainboltgreene** [comment]
Alright, I'll work on a PR tonight that switches to regular arguments.

**Comment by hannahhoward** [comment]
Hi @krainboltgreene for now we're just gonna make Xing require 2.1 or greater. so you can hold off.

**Comment by hannahhoward** [comment]
Thanks though.
